/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_RegistroAutos;
import java.awt.event.KeyEvent;

/**
 *
 * @author chelvivil
 */
public class GUI_Botones extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Botones
     */  Controlador_FRM_RegistroAutos controlador;
     
    public GUI_Botones() {
        initComponents();
    }
    public void agregarEventos(Controlador_FRM_RegistroAutos controlador){
        this.controlador= controlador;
        this.jb_Agregar.addActionListener(controlador);
        this.jb_Buscar.addActionListener(controlador);
        this.jb_Modificar.addActionListener(controlador);
        this.jb_Eliminar.addActionListener(controlador);
    }
     public void estadoInicial(){
        this.jb_Buscar.setEnabled(true);
        this.jb_Agregar.setEnabled(false);
        this.jb_Eliminar.setEnabled(false);
        this.jb_Modificar.setEnabled(false);
    }
     public void habilitarAgregar()
    {
        this.jb_Buscar.setEnabled(false);
        this.jb_Agregar.setEnabled(true);
        this.jb_Eliminar.setEnabled(false);
        this.jb_Modificar.setEnabled(false);
    }
    
     public void habilitarOpciones()
    {
        this.jb_Buscar.setEnabled(false);
        this.jb_Agregar.setEnabled(false);
        this.jb_Eliminar.setEnabled(true);
        this.jb_Modificar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_Buscar = new javax.swing.JButton();
        jb_Agregar = new javax.swing.JButton();
        jb_Modificar = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();

        jb_Buscar.setText("Buscar");
        jb_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_BuscarKeyPressed(evt);
            }
        });

        jb_Agregar.setText("Agregar");

        jb_Modificar.setText("Modificar");

        jb_Eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_Buscar)
                .addGap(39, 39, 39)
                .addComponent(jb_Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jb_Modificar)
                .addGap(29, 29, 29)
                .addComponent(jb_Eliminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Buscar)
                    .addComponent(jb_Agregar)
                    .addComponent(jb_Modificar)
                    .addComponent(jb_Eliminar))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_BuscarKeyPressed
        if(evt.getKeyCode()==10){
           controlador.buscar();
            
        }
    }//GEN-LAST:event_jb_BuscarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Agregar;
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JButton jb_Eliminar;
    private javax.swing.JButton jb_Modificar;
    // End of variables declaration//GEN-END:variables
}
