/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.MetodosRegistroAutos;

/**
 *
 * @author chelvivil
 */
public class GUI_InformacionRegistro extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionRegistro
     */
   MetodosRegistroAutos metodo;
   
   
    public GUI_InformacionRegistro() {
        initComponents();
    }
   
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String[4];
        arreglo[0]=this.jt_NumeroRegistro.getText();
        arreglo[1]=this.jt_NombreDueño.getText();
        arreglo[2]=this.jt_CedulaDueño.getText();
        arreglo[3]=this.jt_PlacaAuto.getText();
        
        return arreglo;
    }
       public void mostrarInformacion(String arreglo[])
    {
        this.jt_NombreDueño.setText(arreglo[0]);
        this.jt_CedulaDueño.setText(arreglo[1]);
        this.jt_PlacaAuto.setText(arreglo[2]);
        
        
    }
       
       
      public void estadoInicial(){
           this.jt_NumeroRegistro.setText(metodo.numero);
           this.jt_NumeroRegistro.setEnabled(true);
           this.jt_NombreDueño.setEnabled(false);
           this.jt_CedulaDueño.setEnabled(false);
           this.jt_PlacaAuto.setEnabled(false);

       }
      public void limpiarInterfaz(){
           
           this.jt_NombreDueño.setText("");
           this.jt_CedulaDueño.setText("");
           this.jt_PlacaAuto.setText("");
       
      }
       public void habilitarAgregar(){
           this.jt_NumeroRegistro.setEnabled(false);
           this.jt_NombreDueño.setEnabled(true);
           this.jt_CedulaDueño.setEnabled(true);
           this.jt_PlacaAuto.setEnabled(true);
       }
      
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NumeroRegistro = new javax.swing.JLabel();
        jl_NombreDelDueño = new javax.swing.JLabel();
        jl_CedulaDueño = new javax.swing.JLabel();
        jl_PlacaAuto = new javax.swing.JLabel();
        jt_NumeroRegistro = new javax.swing.JTextField();
        jt_NombreDueño = new javax.swing.JTextField();
        jt_CedulaDueño = new javax.swing.JTextField();
        jt_PlacaAuto = new javax.swing.JTextField();

        jl_NumeroRegistro.setText("Numero Registro");

        jl_NombreDelDueño.setText("Nombre del Dueño");

        jl_CedulaDueño.setText("Cedula del Dueño");

        jl_PlacaAuto.setText("Placa Automovil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_NumeroRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_CedulaDueño)
                            .addComponent(jl_PlacaAuto))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_CedulaDueño)
                            .addComponent(jt_PlacaAuto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_NombreDelDueño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jt_NombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NumeroRegistro)
                    .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreDelDueño)
                    .addComponent(jt_NombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_CedulaDueño)
                    .addComponent(jt_CedulaDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_PlacaAuto)
                    .addComponent(jt_PlacaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_CedulaDueño;
    private javax.swing.JLabel jl_NombreDelDueño;
    private javax.swing.JLabel jl_NumeroRegistro;
    private javax.swing.JLabel jl_PlacaAuto;
    private javax.swing.JTextField jt_CedulaDueño;
    private javax.swing.JTextField jt_NombreDueño;
    private javax.swing.JTextField jt_NumeroRegistro;
    private javax.swing.JTextField jt_PlacaAuto;
    // End of variables declaration//GEN-END:variables
}
